<!DOCTYPE html>
<html>
<body>
<section class="regular slider">
<?php
    $collectionData = $block->getResultData();
    foreach($collectionData as $collection):
?>
        <div>
            <img src="<?= $collection->getPath(); ?>" />
        </div>
        <?php endforeach; ?>       
</section>
</body>
</html>


<!-- <table>
    <tr>
        <th><?= __('ID'); ?></th>
        <th><?= __('Banner ID'); ?></th>
        <th><?= __('Path'); ?></th>
        <th><?= __('Created At'); ?></th>
        <th><?= __('Updated At'); ?></th>
    </tr>
    
    <tr>
        <td><?= $collection->getBannerImageId(); ?></td>
        <td><?= $collection->getBannerId(); ?></td>
        <td>
           <img src="<?= $collection->getPath(); ?>" width="50" height="50" />
        </td>
        <td><?= $collection->getCreatedAt(); ?></td>
        <td><?= $collection->getUpdatedAt(); ?></td>
    </tr>

</table> -->
